# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_uniques": "03_prep.ipynb"}

modules = ["prep.py"]

doc_url = "https://sgaseretto.github.io/hybrec/"

git_url = "https://github.com/sgaseretto/hybrec/tree/master/"

def custom_doc_links(name): return None
