# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/03_prep.ipynb (unless otherwise specified).

__all__ = ['get_uniques']

# Cell
def get_uniques(df, column=None):
    try:
        if column == None and len(df.shape):
            return df.unique()
        return df[column].unique()
    except:
        print('ERROR: No se paso una columna del Dataframe o no se paso el nombre de la columna')